name: "Docker Image Build"
  
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types:
      - opened
      - synchronize
      - reopened
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    env:
      app_name: commerce-app-demo
      service_name: order-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set GOPRIVATE
        run: echo "GOPRIVATE=github.com/commerce-app-demo/*" >> $GITHUB_ENV
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: asia-southeast2-docker.pkg.dev/${{ env.app_name }}/${{ env.service_name }}
          username: _json_key
          password: ${{ secrets.PUSHER_SECRET }}
        
      - name: Staging Order Service Docker Image
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: order-service-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            git_credentials=https://x-access-token:${{ secrets.GH_PAT }}@github.com

      - name: Production Order Service Docker Image
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: main-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            git_credentials=https://x-access-token:${{ secrets.GH_PAT }}@github.com
